# Created using wingetcreate 1.9.0.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: abc.abc
PackageVersion: 1.26.400.0
Platform:
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.11.400/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 427D60BDDCC36E0115145682AF07B5A1E77AA5BFA555748B695C0BC0D76AA599
  SignatureSha256: 2215B690C54B5371EFC931572BECC8ED7450C1CCDC7F56A51EE712F4B62ACCA4
- Architecture: x86
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.11.400/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 427D60BDDCC36E0115145682AF07B5A1E77AA5BFA555748B695C0BC0D76AA599
  SignatureSha256: 2215B690C54B5371EFC931572BECC8ED7450C1CCDC7F56A51EE712F4B62ACCA4
- Architecture: arm64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.11.400/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 427D60BDDCC36E0115145682AF07B5A1E77AA5BFA555748B695C0BC0D76AA599
  SignatureSha256: 2215B690C54B5371EFC931572BECC8ED7450C1CCDC7F56A51EE712F4B62ACCA4
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-06-18
